language: java
jdk:
  - openjdk8

branches:
  only:
    - main

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r backend *
  - mkdir -p deploy
  - mv backend.zip deploy/backend.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: kurlabo-springboot-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true
    on:
      branch: main

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: kurlabo-springboot-build
    key: backend.zip
    bundle_type: zip
    application: backend
    deployment_group: kurlabo-backend-group
    region: ap-northeast-2
    wait-until-deployed: true
    on:
      branch: main

before_install:
  - chmod +x gradlew

notifications:
  email:
    recipients:
      - 'kurlabobackend@gmail.com'