version: 0.0
os: linux
files:
  - source: /
    destination: /opt/codedeploy-agent/deployment-root/kurlabo-backend/ # 프로젝트 이름
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStart:
  - location: scripts/deploy.sh
    timeout: 60
    runas: root
