spring:
#  profiles:
#    include: oauth, real-db
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://kurlabo-rds.c7mbllne7stz.ap-northeast-2.rds.amazonaws.com:3306/kurlaboDB?user=lnoah&password=tkdrud1dnjf!
    username: lnoah
    password: tkdrud1dnjf!
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    show-sql: true
  session:
    store-type: jdbc
    timeout: 3600

jwt:
  header: Authorization
  secret: 4oCYa3VybGFiby1iYWNrZW5kLWNsb25lcHJvamVjdC1zcHJpbmctYm9vdC1qd3Qtc2VjcmV0LWt1cmxhYm8tYmFja2VuZC1jbG9uZXByb2plY3Qtc3ByaW5nLWJvb3Qtand0LXNlY3JldOKAmQo=
  token-validity-in-seconds: 3600